@startuml
object TabsView
object SuggestionsView
object ContextMenuView
object RhymerView
object ThesaurusView
object DefinitionsView
object ReaderView
object VoiceSettingsView
object MainView

object MainViewModel
object RhymerViewModel
object ThesaurusViewModel
object DefinitionsViewModel
object ReaderViewModel
object SuggestionsViewModel

object MainModel
object RhymerRepository
object ThesaurusRepository
object DefinitionsRepository
object PoemRepository
object SuggestionsRepository
object SpeechEngine


object Db
object Settings

TabsView <.. MainView
ContextMenuView <.. MainView
RhymerView <.. MainView
ThesaurusView <.. MainView
DefinitionsView <.. MainView
ReaderView <.. MainView
VoiceSettingsView <.. MainView
SuggestionsView <.. MainView
MainView ..> MainViewModel
MainView ..> ReaderViewModel

MainViewModel ..> MainModel
MainViewModel ..> RhymerViewModel
MainViewModel ..> ThesaurusViewModel
MainViewModel ..> DefinitionsViewModel
MainViewModel ..> SuggestionsViewModel

RhymerViewModel ..> RhymerRepository
ThesaurusViewModel ..> ThesaurusRepository 
DefinitionsViewModel ..> DefinitionsRepository
ReaderViewModel ..> PoemRepository
ReaderViewModel ..> SpeechEngine
SuggestionsViewModel ..> SuggestionsRepository


RhymerRepository ..> Db
ThesaurusRepository ..> Db
DefinitionsRepository ..> Db
SuggestionsRepository ..> Db
RhymerRepository ..> Settings
ThesaurusRepository ..> Settings
PoemRepository ..> Settings
SuggestionsRepository ..> Settings
SpeechEngine ..> Settings

@enduml
