@startuml
object TabsView
object SuggestionsView
object ContextMenuView
object RhymerView
object ThesaurusView
object DefinitionsView
object ReaderView
object VoiceSettingsView
object MainView

object MainViewModel
object RhymerViewModel
object ThesaurusViewModel
object DefinitionsViewModel
object ReaderViewModel
object SuggestionsViewModel

object MainModel
object RhymerRepository
object ThesaurusRepository
object DictionaryRepository
object SuggestionsRepository
object SpeechEngine


object Db

TabsView <.. MainView
ContextMenuView <.. MainView
RhymerView <.. MainView
ThesaurusView <.. MainView
DefinitionsView <.. MainView
ReaderView <.. MainView
VoiceSettingsView <.. MainView
SuggestionsView <.. MainView
MainView ..> MainViewModel

MainViewModel ..> MainModel
MainViewModel ..> RhymerViewModel
MainViewModel ..> ThesaurusViewModel
MainViewModel ..> DefinitionsViewModel
MainViewModel ..> ReaderViewModel
MainViewModel ..> SuggestionsViewModel

RhymerViewModel ..> MainModel
ThesaurusViewModel ..> MainModel
DefinitionsViewModel ..> MainModel
ReaderViewModel ..> MainModel
SuggestionsViewModel ..> MainModel

MainModel ..> SpeechEngine
MainModel ..> RhymerRepository
MainModel ..> ThesaurusRepository 
MainModel ..> DictionaryRepository
MainModel ..> SuggestionsRepository

RhymerRepository ..> Db
ThesaurusRepository ..> Db
DictionaryRepository ..> Db
SuggestionsRepository ..> Db

@enduml
