@startuml
object TabsView
object SuggestionsView
object ContextMenuView
object RhymerView
object ThesaurusView
object DefinitionsView
object FavoritesView
object ReaderView
object VoiceSettingsView
object MainView

object MainViewModel

object MainModel
object RhymerRepository
object ThesaurusRepository
object DefinitionsRepository
object FavoritesRepository
object SuggestionsRepository
object PoemRepository
object SpeechEngine


object Db
object Settings

TabsView <.. MainView
ContextMenuView <.. MainView
RhymerView <.. MainView
ThesaurusView <.. MainView
DefinitionsView <.. MainView
FavoritesView <.. MainView
ReaderView <.. MainView
VoiceSettingsView <.. MainView
SuggestionsView <.. MainView
MainView ..> MainViewModel

MainViewModel ..> MainModel

MainModel ..> SpeechEngine
MainModel ..> RhymerRepository
MainModel ..> ThesaurusRepository 
MainModel ..> DefinitionsRepository
MainModel ..> FavoritesRepository
MainModel ..> SuggestionsRepository
MainModel ..> PoemRepository

RhymerRepository ..> Db
ThesaurusRepository ..> Db
DefinitionsRepository ..> Db
SuggestionsRepository ..> Db

RhymerRepository ..> Settings
ThesaurusRepository ..> Settings
FavoritesRepository ..> Settings
SuggestionsRepository ..> Settings
PoemRepository ..> Settings
SpeechEngine ..> Settings

@enduml
